version: "3.7"

services:
    flask:
        build: ./appserver
        container_name: flask
        restart: always
        network_mode: host

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        network_mode: host