server {
        listen 20000;
        server_name localhost;
        client_max_body_size 1M;

        location / {
                include uwsgi_params;
                uwsgi_pass flask:19999;
        }
}
